### PR TITLE
Stripe needs precheckout validation

### PR DESCRIPTION
**Pull request by ryanmitchell**
See PR on cart

### CODE REVIEW

**Comment by sampoyigi** [comment]
I think this should return true only when the Stripe payment request button is available and not by default since its not required for the current flow.

**Comment by ryanmitchell** [comment]
It will be required for the payment intents change as all the processing will be done client side

**Comment by sampoyigi** [comment]
Together with 3D authentication?

**Comment by ryanmitchell** [comment]
Yeah it mostly all happens client side with payment intents. There is still the possibility of a redirect url which is why I left that logic in

**Comment by sampoyigi** [comment]
Nothing to merge

**Pull request closed without merging**
