### PR TITLE
Support Stripe PaymentRequestButton

### PR DESCRIPTION
**Pull request by ryanmitchell**
Keen to add support for 1 click checkouts (Apple Pay, Google Pay etc) to streamline the experience for end users.
https://stripe.com/docs/stripe-js/elements/payment-request-button

I've added the first stage of JS (up to and included step 3 at the link above).

Need some guidance on how to handle steps 4 and 5 within the confines of the current pay register code. Can you guide me at all?

**Update**: I'm not sure support is there in Omnipay/Stripe for this yet. So we may have to roll our own CURL/Guzzle call for Step 4.

### CODE REVIEW

**Comment by sampoyigi** [comment]
This is awesome! Any chance Square gets some love too? That's if they support the payment buttons.

**Comment by ryanmitchell** [comment]
Yep I can look at Square once this is complete. Let me know how you want me to handle steps 4 and 5 in Stripe so I can finish this one off.

**Comment by sampoyigi** [comment]
Handling step 4 and 5 will require some changes to the current payment flow to allow the PaymentIntent to be created before the payment form is rendered and then passed to the form as a hidden field. Currently the payment gets created and sent when the payment form is submitted, so if we have the PaymentIntent created and passed to the form somewhere in `getHiddenFields` and then check the PaymentIntent.status within processPaymentForm. Let me know if that helps..

**Comment by sampoyigi** [comment]
Let me add some scaffolding to explain better.

**Comment by ryanmitchell** [comment]
Yeah that makes sense - I think putting it in the session would be safer to prevent a user being able to modify the field? 

Any ideas on what method to use on omnipay/stripe to actually create an intent? the documentation is so out of date .... !!

**Comment by sampoyigi** [comment]
Right the PaymentIntent doesn't have the create request. I have a fork of the omnipay-stripe i'm maintaining, you can look into it to add the missing create PaymentIntent message class to have it supported.

**Comment by ryanmitchell** [comment]
Yeah I’ll have a go.
Leave it with me.

**Comment by ryanmitchell** [comment]
Ok, I've pushed changes and will open a PR on the omnipay fork too. Let me know what you think of this approach.

I came across an issue/bug in that if the email address has already been used or there is any other on the customer fields payment will be taken but the order not processed. Any thoughts on how to handle that?

**Comment by sampoyigi** [comment]
Good approach... Maybe separating the payment form logic from the button logic. We could add a new processPaymentButton method to handle that and follow same approach as payFromPaymentProfile()?

**Comment by ryanmitchell** [comment]
That just means adding a change to cart/OrderManager to check for a field like payment_button and then calling the new function? That would work.

I don't know if you meant that change would fix the issue I mentioned, as it wouldn't. The payment is taken on the client side with these payment buttons, so by the time the server side processing is done its already been authorised. It may just be a case of refunding or voiding the payment intent if there is an error. The only other option I can think of is validating the customer fields on the client side.

**Comment by sampoyigi** [comment]
So after taking payment on the client-side, cant we redirect to the server to mark the order as complete?

**Comment by ryanmitchell** [comment]
I don’t think so unfortunately. It seems to take the payment on client side and there is no option of server side confirmation according to the docs.

**Comment by sampoyigi** [comment]
Yea I mean calling `$order->markAsProcessed()` from the server-side after taking payment.

**Comment by ryanmitchell** [comment]
Yep sorry, misunderstood what you meant.

Also called updateOrderStatus as that seemed to be needed - let me know if not.

**Comment by ryanmitchell** [comment]
Do you have access to a Square test account - so I can work on that next?

**Comment by ryanmitchell** [comment]
Sorry, just following up on this again. Did you get a chance to test it on your side - if we can figure out the issue with sqPaymentForm setup then this should be good to go.

**Comment by sampoyigi** [comment]
Oh not yet, trying to get the next update out the way first I will definitely come back to this at some point to test and do a proper review 😅 .

**Review by sampoyigi — CHANGES_REQUESTED** [review]
Got stuck with this one, how do I test the payment button? I tried on an iPad and iPhone but no luck, I only get the payment form.

**Comment by ryanmitchell** [comment]
Are you using test mode in stripe?
You might need to verify your domain to get it to appear. 
See here:
https://stripe.com/docs/stripe-js/elements/payment-request-button

**Comment by ryanmitchell** [comment]
So I've found an issue with this, and could do with your thoughts on how best to get around it.

As the payment is confirmed client side, rather than server side, if you take a successful payment but there is an issue with the other form fields (email etc), then we take payment but the order throws an error, which is obviously pretty bad.

There are a few approaches I can think of to fix this:

1. We could split out payment onto a second checkout step, so you take customer details, then payment details. This allows us to validate non payment first, then validate payment client side. The downside is add a bit of friction to the process.

2. Before processing payment we could do a JS request and check the non payment fields validate, and if they don't we show which fields need fixed?

3. Add an intermediate response in the processPaymentButton() server side, where we output the JS that actually confirms the order, and on success is posts again (in JS) which actually inserts the order. This feels like the best approach, but might need some changes to cart/OrderManager to allow processPayment() to have an intermediate page?

4. Not support client-side payment buttons :)

Let me know if I've explained this well enough!

**Comment by sampoyigi** [comment]
Yea its a bit tricky this one! I'd say let's not support it but you've already put in a lot of work, so maybe we put it on hold until after we have a stable version?

**Comment by ryanmitchell** [comment]
Yeah I'm happy to park it until we have capacity to think it through.

**Comment by ryanmitchell** [comment]
@sampoyigi Just a heads up I'm going to loop back around and finalise this if/when precheckout authorisation gets merged.

**Pull request closed without merging**
