### PR TITLE
Don't assume code is always "stripe"

### PR DESCRIPTION
**Pull request by ryanmitchell**
Corresponding change coming to the theme file

### CODE REVIEW

**Comment by ryanmitchell** [comment]
The data-trigger-condition on #stripePaymentForm needs changed to have value of ="value[<?= $paymentMethod->code; ?>]", but it seems you've updated the approach to this?

**Comment by sampoyigi** [comment]
I don't think this is a necessary change as the process.stripe.js should only work for the stripe payment. `value=stripe` should work fine except you save the payment with a different code in the admin.

**Comment by ryanmitchell** [comment]
Yep that’s our use case. 

We have a restaurant group with multiple locations - each with a different stripe account but under the same TI instance.

Seems like something we should cover off as it’s a small fix?

**Comment by sampoyigi** [comment]
I've been able to use the current payment form with Stripe Connect by listening on the 'payregister.stripe.extendFields` event, you could follow the same approach if that's what you're trying. 

Hardcoding the payment code into the partials and JS files was intentional to force developers to either extend the partials or JS file when extending a payment to avoid conflicting issues. The idea is that each payment gateway has a single unique payment code, instead of having multiple payment codes link to a single payment gateway.

I know it seems a small fix and doesn't change much but I'd rather leave it since its working as expected.

**Comment by ryanmitchell** [comment]
No problem - thanks for the explanation.

**Pull request closed without merging**
